config/routes.rb
Rails.application.routes.draw do
  resources :people
	get 'customers/check_email_present'
	get 'customers/check_mobile_present'
	get 'states/get_cities'
	get 'states/check_name_present'
	root to: 'customers#index'
  resources :customers
  resources :cities
  resources :states
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/state.rb
class State < ApplicationRecord
	has_many :cities
	has_many :customers
	has_many :people
	validates_presence_of :name
end

app/controllers/states_controller.rb
class StatesController < ApplicationController
  before_action :set_state, only: [:show, :edit, :update, :destroy]

  # GET /states
  # GET /states.json
  def index
    @states = State.all
    @state = State.new
  end

  # GET /states/1
  # GET /states/1.json
  def show
  end

  # GET /states/new
  def new
    @state = State.new
  end

  # GET /states/1/edit
  def edit
  end

  # POST /states
  # POST /states.json
  def create
    @state = State.new(state_params)

    respond_to do |format|
      if @state.save
        format.js
        format.html { redirect_to @state, notice: 'State was successfully created.' }
        format.json { render :show, status: :created, location: @state }
      else
        format.js
        format.html { render :new }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /states/1
  # PATCH/PUT /states/1.json
  def update
    respond_to do |format|
      if @state.update(state_params)
        format.html { redirect_to @state, notice: 'State was successfully updated.' }
        format.json { render :show, status: :ok, location: @state }
      else
        format.html { render :edit }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /states/1
  # DELETE /states/1.json
  def destroy
    @state.destroy
    respond_to do |format|
      format.html { redirect_to states_url, notice: 'State was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def get_cities
    @state = State.find(params[:state_id])
    render json: @state.cities
  end
 def check_name_present
  @state = State.find_by(name: params[:name])
  render json: @state.nil? ? {'msg':'can be used'} : {'msg':'already taken'}
 end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_state
      @state = State.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def state_params
      params.require(:state).permit(:name)
    end
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/states/_error.html.erb
<% if @state.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@state.errors.count, "error") %> prohibited this state from being saved:</h2>
      <ul>
      <% @state.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
<% end %>

app/views/states/_form.html.erb
<%= form_for(state, remote: true) do |form| %>
  <% if state.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(state.errors.count, "error") %> prohibited this state from being saved:</h2>
      <ul>
      <% state.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :state_name %><span id="nameErroror"></span>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
<script>
  var nameHandler = document.getElementById('state_name');
  var nameErrorHandler = document.getElementById('nameErroror');
  nameHandler.addEventListener('blur',function(){
    var xhr = new XMLHttpRequest();
    xhr.open('GET','/states/check_name_present?name='+nameHandler.value,true);
    xhr.onreadystatechange = function(){
      if(xhr.readyState === 4 && xhr.status === 200){
        var response = JSON.parse(xhr.responseText);
        nameErrorHandler.innerHTML = response.msg;
      }
    }
    xhr.send();
  },false);
  nameHandler.addEventListener('focus',function(){
    nameErrorHandler.innerHTML = "";
  },true);
</script>

app/views/states/_state.html.erb
<tr>
    <td><%= @state.name %></td>
    <td><%= link_to 'Show', @state %></td>
    <td><%= link_to 'Edit', edit_state_path(@state) %></td>
    <td><%= link_to 'Destroy', @state, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/states/create.js.erb
<%if @state.valid?%>
    $('#new_state')[0].reset();
	$('#body').append("<%= escape_javascript render 'state'%>");
<%else%>
	$('#error').html("<%=escape_javascript render 'error'%>");
<%end%>

app/views/states/edit.html.erb
<h1>Editing State</h1>

<%= render 'form', state: @state %>

<%= link_to 'Show', @state %> |
<%= link_to 'Back', states_path %>

app/views/states/index.html.erb
<p id="notice"><%= notice %></p>
<h1>States</h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody id = "body">
    <% @states.each do |state| %>
      <tr>
        <td><%= state.name %></td>
        <td><%= link_to 'Show', state %></td>
        <td><%= link_to 'Edit', edit_state_path(state) %></td>
        <td><%= link_to 'Destroy', state, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New State', new_state_path %>
<div id="error"></div>
<%= render 'form',state: @state%>

app/views/states/new.html.erb
<h1>New State</h1>

<%= render 'form', state: @state %>

<%= link_to 'Back', states_path %>

app/views/states/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @state.name %>
</p>

<%= link_to 'Edit', edit_state_path(@state) %> |
<%= link_to 'Back', states_path %>