config/routes.rb
Rails.application.routes.draw do
  resources :people
	get 'customers/check_email_present'
	get 'customers/check_mobile_present'
	get 'states/get_cities'
	get 'states/check_name_present'
	root to: 'customers#index'
  resources :customers
  resources :cities
  resources :states
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
	belongs_to :state
	belongs_to :city 
	
	validates_presence_of :name, :email, :mobile, :state_id, :city_id
	validates_uniqueness_of :email, :mobile
	validates_length_of :mobile, is: 10
	validates_numericality_of :mobile
	validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_customer, only: [:show, :edit, :update, :destroy]
  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all.limit(10)
    @customer = Customer.new  
    @state = State.new
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)
    if @customer.save
        # render json: {name:@customer.name,mobile:@customer.mobile,email:@customer.email,state_name:@customer.state.name,
        # city_name:@customer.city.name,state_id:@customer.state_id,city_id:@customer.city_id}
        render json: @customer.attributes.merge(state_name:@customer.state.name,city_name:@customer.city.name,customer_count:Customer.count);
    else
      render json:{error: @customer.errors.full_messages}
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def check_email_present
    @email = Customer.find_by(email:params[:email])
    render json: @email.nil? ? {'msg':"can be used"} : {'msg':'already taken'}
  end
  def check_mobile_present
    @mobile = Customer.find_by(mobile:params[:mobile])
    render json: @mobile.nil? ? {'msg':"can be used"} : {'msg':'already taken'}
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:state_id, :city_id, :name, :email, :mobile)
    end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<%= form_with(model: customer, local: true,id:'customer_form') do |form| %>
  <% if customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :state_id%>
    <%= form.collection_select :state_id, State.all, :id, :name, {prompt: "Select"}, {id: :customer_state_id} %><span id="stateError"></span>
  </div>
  <div class="field">
    <%= form.label :city_id %>
    <%= form.collection_select :city_id, City.all, :id, :name, {prompt: "Select"}, {id: :customer_city_id} %><span id="cityError"></span>
  </div>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :customer_name%><span id="nameError"></span>
  </div>
  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :customer_email %><span id="emailError"></span>
  </div>
  <div class="field">
    <%= form.label :mobile %>
    <%= form.text_field :mobile, id: :customer_mobile %><span id="mobileError"></span>
  </div>
  <div class="actions">
    <%= form.submit  id:'submit'%>
  </div>
<% end %>
<script>
  var numberFormat = /^\d+$/;
  var emailFormat = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
  var nameFormat = /^[a-zA-Z]*$/;
  var stateHandle = document.getElementById('customer_state_id');
  var cityHandle = document.getElementById('customer_city_id');
  var nameHandle = document.getElementById('customer_name');
  var emailHandle = document.getElementById('customer_email');
  var mobileHandle = document.getElementById('customer_mobile');
  var formHandle = document.getElementById('customer_form');
  var stateErrorHandle = document.getElementById('stateError');
  var cityErrorHandle = document.getElementById('cityError');
  var nameErrorHandle = document.getElementById('nameError');
  var emailErrorHandle = document.getElementById('emailError');
  var mobileErrorHandle = document.getElementById('mobileError');
  var submitHandle = document.getElementById('submit');
  var bodyHandle = document.getElementById('body');
  var validator = {
    stateValid: false,
    cityValid: false,
    nameValid: false,
    emailValid: false,
    mobileValid: false
  }
  function stateValidation(){
    if(stateHandle.value === ""){
      validator.stateValid = false;
      stateErrorHandle.innerHTML = "can't be blank";
    }else{
      validator.stateValid = true;
      stateErrorHandle.innerHTML = "";
    }
  }
  function cityValidation(){
    if(cityHandle.value === ""){
      validator.cityValid = false;
      cityErrorHandle.innerHTML = "can't be blank";
    }else{
      validator.cityValid = true;
      cityErrorHandle.innerHTML = " ";
    }
  }
  function nameValidation(){
    if(nameHandle.value === ""){
      validator.nameValid = false;
      nameErrorHandle.innerHTML = "can't be blank";
    }else if(!nameFormat.test(nameHandle.value)){
      validator.nameValid = false;
      nameErrorHandle.innerHTML = "should only be alphabets";
    }
    else{
      validator.nameValid = true;
      nameErrorHandle.innerHTML = "";
    }
  }
  function emailValidation(response){
    if(emailHandle.value === ""){
      validator.emailValid = false;
      emailErrorHandle.innerHTML = "can't be blank";
    }else if(!emailFormat.test(emailHandle.value)){
      validator.emailValid = false;
      emailErrorHandle.innerHTML = "should be a valid email";
    }
    else if(response.msg === 'already taken'){
        validator.emailValid = false;
        emailErrorHandle.innerHTML = response.msg;
    }else{
      validator.emailValid = true;
      emailErrorHandle.innerHTML = "";
    }  
  }
  function mobileValidation(response){
    if(mobileHandle.value === ""){
      validator.mobileValid = false;
      mobileErrorHandle.innerHTML = "can't be blank";
    }else if(!numberFormat.test(mobileHandle.value)){
      validator.mobileValid = false;
      mobileErrorHandle.innerHTML = "should be a number";
    }else if(mobileHandle.value.length !== 10){
       mobileErrorHandle.innerHTML =  "should be 10 digits";
    }else if(response.msg === 'already taken'){
       validator.mobileValid = false;
       mobileErrorHandle.innerHTML = response.msg;
    }else{
      validator.mobileValid = true;
      mobileErrorHandle.innerHTML = "";
    }
  }
  formHandle.addEventListener('submit',function(e){
    stateValidation();
    cityValidation();
    nameValidation();
    if(Object.values(validator).includes(false)){
       e.preventDefault();
       setTimeout(function(){
        submitHandle.disabled = false;
      },100);
    }else{
      e.preventDefault();
      var formData = {
        "utf8": formHandle.elements[0].value,
        "authenticity_token":formHandle.elements[1].value,
        "customer": {
          "name": nameHandle.value,
          "mobile": mobileHandle.value,
          "email": emailHandle.value,
          "state_id": stateHandle.value,
          "city_id": cityHandle.value
        }
      }
      var xhr = new XMLHttpRequest()
      xhr.open('POST','/customers',true);
      xhr.onreadystatechange = function(){
        if(xhr.readyState === 4 && xhr.status === 200){
          customer = JSON.parse(xhr.responseText);
          formHandle.reset();
          setTimeout(function(){
            submitHandle.disabled = false;
          },100);
          tr = document.createElement('tr');
          stateTd = document.createElement('td');//<td></td>
          stateText = document.createTextNode(customer.state_name); //1
          stateTd.appendChild(stateText);//<td>1</td>
          tr.appendChild(stateTd);//<tr><td>1</td></tr>
          cityTd = document.createElement('td');
          cityText = document.createTextNode(customer.city_name); 
          cityTd.appendChild(cityText);
          tr.appendChild(cityTd);
          nameTd = document.createElement('td');
          nameText = document.createTextNode(customer.name);
          nameTd.appendChild(nameText);
          tr.appendChild(nameTd);
          body.appendChild(tr);
          document.querySelector('#count').innerText = customer.customer_count
        }
      }
      xhr.setRequestHeader('Content-Type','application/json');
      xhr.send(JSON.stringify(formData)); 
     }  
  },false);
  stateHandle.addEventListener('change',function(){
    var state_id = stateHandle.value
    if(state_id !== ""){
      var xhr = new XMLHttpRequest();
      xhr.open('GET',`/states/get_cities?state_id=${state_id}`,true);
      xhr.onreadystatechange = function(){
        if(xhr.readyState === 4 && xhr.status === 200 ){
          var cities = JSON.parse(xhr.responseText);
          cityHandle.innerHTML = "";
          cities.forEach(function(city){
            var option = document.createElement('option');
            var optionattr = document.createAttribute('value');
            optionattr.value = city.state_id;
            option.setAttributeNode(optionattr);
            var text = document.createTextNode(city.name);
            option.appendChild(text);
            cityHandle.appendChild(option);
          });
        }
      }
      xhr.send();
    }
  },false);
emailHandle.addEventListener('blur',function(){
      var xhr = new XMLHttpRequest();
      xhr.open('GET','/customers/check_email_present?email='+emailHandle.value,true);
      xhr.onreadystatechange = function(){
        if(xhr.readyState === 4 && xhr.status === 200){
          var response = JSON.parse(xhr.responseText);      
          emailValidation(response)
        }
      }
      xhr.send();
},false);
mobileHandle.addEventListener('blur',function(){
  var xhr = new XMLHttpRequest();
  xhr.open('GET','/customers/check_mobile_present?mobile='+mobileHandle.value,true);
  xhr.onreadystatechange = function(){
    if(xhr.readyState === 4 && xhr.status === 200){
      var response = JSON.parse(xhr.responseText);
      mobileValidation(response);
    }
  }
  xhr.send();
},false);
emailHandle.addEventListener('focus',function(){
          emailErrorHandle.innerHTML = "";
      },false);
mobileHandle.addEventListener('focus',function(){
          mobileErrorHandle.innerHTML = "";
      },false);
</script>

app/views/customers/destroy.js.erb
$('customer_<%=@customer.id%>').hide();

app/views/customers/edit.html.erb
<h1>Editing Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Customers<span id="count"><%=@customers.count%></span></h1>
<table id="customerTable">
  <thead>
    <tr>
      <th>State</th>
      <th>City</th>
      <th>Name</th>
      <th>Email</th>
      <th><MAP></MAP>mobile</th>
      <th></th>
    </tr>
  </thead>
  <tbody id="body">
    <%@customers.each do |customer| %>
      <tr id="customer_<%=customer.id%>">
        <td><%= customer.state.name %></td>
        <td><%= customer.city.name %></td>
        <td><%= customer.name %></td>
        <td><%= customer.email %></td>
        <td><%= customer.mobile %></td>
        <td><%= link_to 'Show', customer %>
        <%= link_to 'Edit', edit_customer_path(customer) %>
        <%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' },remote: true%>
        </td>
      </tr>
    <%end%>
  </tbody>
</table>
<br>
<h2>add new customer</h2>
<%= render 'form',customer: @customer%>
<h2>add new state</h2>
<%= render '/states/form',state: @state%>
<script>
  $('#customerTable').DataTable();
</script>

app/views/customers/new.html.erb
<h1>New Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>State:</strong>
  <%= @customer.state.name %>
</p>

<p>
  <strong>City:</strong>
  <%= @customer.city.name %>
</p>

<p>
  <strong>Name:</strong>
  <%= @customer.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @customer.email %>
</p>

<p>
  <strong>Mobile:</strong>
  <%= @customer.mobile %>
</p>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>